cask "coral" do
  arch arm: "aarch64", intel: "x86_64"
  os macos: "apple-darwin", linux: "unknown-linux-gnu"

  version "0.15.4"
  sha256 arm:          "83d2b6c7ba5110108f3a4ed382e3afdb9e4a7c4357836f4624d263a5d5fd48d4",
         intel:        "d36613fec8463a1c777125566a21271fb3b0a24f6275b82fdbc0226f415c800c",
         arm64_linux:  "d3108fd94a62666a5954cd24803b3e80691615d959eb739cf759292cc2da45fe",
         x86_64_linux: "5bd9270ed6cf583bacbdcdffe4adb89fe0f562d6793fe57dbd8769ffb81773d3"

  url "https://github.com/withcoral/coral/releases/download/v#{version}/coral-#{arch}-#{os}.tar.gz"
  name "Coral"
  desc "Is a single interface for AI agents to query external systems"
  homepage "https://github.com/withcoral/coral"

  livecheck do
    skip "Autogenerated on release"
  end

  binary "coral"
  generate_completions_from_executable("coral", "completion", shells: [:bash, :zsh, :fish])

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coral"] if OS.mac?
  end
end
