cask "coral" do
  version "0.1.1"

  name "Coral"
  desc "Is a single interface for AI agents to query external systems"
  homepage "https://github.com/withcoral/coral"

  livecheck do
    skip "Autogenerated on release"
  end

  binary "coral"

  # generate_completions_from_executable "coral",
  #   shell_parameter_format: :clap

  on_macos do
    on_intel do
      sha256 "5fca98d0da9b2277b24d1fca04514553eb8806ef4aee7efa998209cc137235fe"
      url "https://github.com/withcoral/coral/releases/download/v#{version}/coral-x86_64-apple-darwin.tar.gz"
    end
    on_arm do
      sha256 "3d5287b0af4b401a7a3846dcfb8d79d4b441ca4cc990f7b1fa034bdc5f87cd26"
      url "https://github.com/withcoral/coral/releases/download/v#{version}/coral-aarch64-apple-darwin.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f410c7e14a9e67a716ebc041bfca3c9e61f6dd35fefa3cb50225ce182a2dd4b1"
      url "https://github.com/withcoral/coral/releases/download/v#{version}/coral-x86_64-unknown-linux-gnu.tar.gz"
    end
    on_arm do
      sha256 "d417968e3f892805668993dc6f47a203a80c55f6dcaf11af8a02a3a03a1cea6c"
      url "https://github.com/withcoral/coral/releases/download/v#{version}/coral-aarch64-unknown-linux-gnu.tar.gz"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coral"] if OS.mac?
  end
end
