cask "coral" do
  version "0.2.0"

  name "Coral"
  desc "Is a single interface for AI agents to query external systems"
  homepage "https://github.com/withcoral/coral"

  livecheck do
    skip "Autogenerated on release"
  end

  binary "coral"

  on_macos do
    on_intel do
      sha256 "d10a9e43d5caea16ad53a66600db12ae70bcf02c63c032af6ba548d0f410760a"
      url "https://github.com/withcoral/coral/releases/download/v#{version}/coral-x86_64-apple-darwin.tar.gz"
    end
    on_arm do
      sha256 "3774d44344d4cc9ec4967837cb64a9f3d71030567e2ebcbdf5b6033fdea056f0"
      url "https://github.com/withcoral/coral/releases/download/v#{version}/coral-aarch64-apple-darwin.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "76836316522fc81c95a5c4fb715c0ed83a28f5f694023bef3f3c75b41538b507"
      url "https://github.com/withcoral/coral/releases/download/v#{version}/coral-x86_64-unknown-linux-gnu.tar.gz"
    end
    on_arm do
      sha256 "99420c5366a02d151b6b6d3403708d0d8b70a17421d905e9f46b745e6984d077"
      url "https://github.com/withcoral/coral/releases/download/v#{version}/coral-aarch64-unknown-linux-gnu.tar.gz"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coral"] if OS.mac?
  end

  generate_completions_from_executable("coral", "completion", shells: [:bash, :zsh, :fish])
end
